### PR TITLE
Support Channel Passwords

### PR DESCRIPTION
**Pull request by tsenart**
You can now declare channel passwords on the channel string as "#mychannel:mychannelpassword"

### CODE REVIEW

**Comment by gf3** [comment]
Hot! Thank you.

**Comment by tsenart** [comment]
;)

**Comment by tsenart** [comment]
Can you merge and update the npm package? I am really needing that. Thanks

**Comment by gf3** [comment]
On it, my friend.

**Comment by tsenart** [comment]
Cool. And it is not important but if you don't mind add me to the contributors list if you consider me one eheh. :P

**Pull request merged**
