### PR TITLE
Added `joinOn` option, which takes a raw IRC protocol code and triggers the on-connect stuff (much better than waiting for ping)

### PR DESCRIPTION
**Pull request by peol**
Added an additional 'trigger on-connect' override called `joinOn`, which accepts a raw IRC protocol code

### CODE REVIEW

**Comment by jsyrjala** [comment]
Some servers are completely silent until the client sends some message. See https://github.com/gf3/IRC-js/commit/bfa34db

**Comment by peol** [comment]
So this issue is completely fixed by that commit?

**Comment by peol** [comment]
God damn GH, don't have "Comment & close" closest to the textbox :P

**Comment by jsyrjala** [comment]
Oops, no. That commit is about different level of connecting. But I think that Jerk should listen for 'connected' event at that point instead of waiting to receive some irc message.

**Comment by peol** [comment]
Indeed, the problem is that the `connected` stuff isn't available everywhere. Most servers accepts the client spamming JOIN etc. before actually being fully connected, but the fallback being PING/PONG, this is a better alternative (just look up a RAW IRC code that specific server is spitting out).

**Comment by jsyrjala** [comment]
Hmm, connected event is issued by irc-js when it has sent ( asynchronously ) the login commands to the server. Maybe it should issue the event after the server has accepted the login. Note that connected event is distinct from the connect even emitted by the networking lib.

**Comment by peol** [comment]
Yeah, you're right. I think it should fire after the login stuff has been sent, that's what `connected` means in my world when it comes to IRC :)

**Pull request closed without merging**
