### PR TITLE
SSL

### PR DESCRIPTION
**Pull request by scoates**
Hello. This adds basic SSL support.

S

### CODE REVIEW

**Comment by broofa** [comment]
Sweet!  Diff looks good to me.  Any ETA on when this will get merged?

**Comment by gf3** [comment]
Very soon.

**Comment by gf3** [comment]
Although, I just realised that this is on the wrong repo. This should be on [IRC-js](https://github.com/gf3/IRC-js).

**Comment by gf3** [comment]
I added your commit to IRC-js via patch, and I've updated Jerk to the latest IRC-js. So it's available now.

**Pull request merged**
